<?php

// This class defines the basic functionality needed to process and display a web-page.

// To create a new JsonScript object, call new JSONscript($scrpit) where $script is
// the name of a .js file located in ajax/scripts/. ex: new JSONscript('map');

// To execute the script file, call the execute() method of the JsonScript object.

class JsonScript
{
	// Name of the script to be executed.
	// This string should match the name of some PHP file in WEBROOT/ajax/scripts/
	public $name;
	
	// An associative array of data generated by the script to be returned as JSON.
	private $data;
	
	private $error = '';
	
	// Class constructor
	function __construct($name)
	{
		$this->name = $this->clean_name($name);
	}
	
	// Run the computations needed for the specified page-content.
	public function execute()
	{
		global $Mysql, $Memcached, $User;
		
		// Include the specified script file.
		include(WEBROOT .'ajax/scripts/'. $this->name .'.php');
		$this->data['ERROR'] = $this->error;
		$this->prepare_response();
	}
	
	public function prepare_response()
	{
		header('Content-type: application/json');
		echo json_encode($this->data);
	}
	
	// If the input string is not a valid content string, return 'home'.
	// Else, return the inputted string.
	private function clean_name($s)
	{
		if ( preg_match('/^[a-z,A-Z,0-9,_]+$/', $s) != 1 )
			return_error('dirty_script_name');
		else if ( !is_file(WEBROOT .'ajax/scripts/'. $s .'.php') )
		{
			// The requested content-file does not exist. Send them home instead.
			return_error('script_not_found');
		}
		else
			return $s;
	}
	
	// Called when content of this page requires the user to be logged in.
	private function require_login()
	{
		global $User;
		
		if ( !$User->logged_in() )
			return_error('login_required');
	}
	
}

?>